### ISSUE TITLE
Labels are offset below transforms

### ISSUE THREAD

**Issue by Poodmund** [sarbian/DebugStuff#5]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67618488-337fd600-f7e8-11e9-8bd0-ebfa9381f675.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/67618489-35e23000-f7e8-11e9-8e60-817b091dc293.png)

![Untitled-3](https://user-images.githubusercontent.com/10106634/67618491-37abf380-f7e8-11e9-9253-14df3f68243c.png)

Let me know if you need any further info. :D

**Comment by sarbian** [comment]
Hum, with default ui scale?

**Comment by Poodmund** [comment]
Yes, 100%.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67618956-c53e1200-f7ed-11e9-9341-d07e25d40b69.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/67618959-c7a06c00-f7ed-11e9-90e6-344553248d10.png)

**Comment by Poodmund** [comment]
I can't get this to occur anymore on a barebones install with just ReStock installed (as per the screenshot above) or on a completely Vanilla install on KSP 1.9.1, therefore, I'm going to close the issue.
