### ISSUE TITLE
All variant collider wireframes are rendered instead of just the wireframe of the selected variant

### ISSUE THREAD

**Issue by Poodmund** [sarbian/DebugStuff#6]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80007008-96afa400-84bd-11ea-8482-02ca5d1d9c86.png)

Above shows the collider wireframes for two different variants in vanilla KSP 1.9.1 with DebugStuff installed. Pretty self-explanatory, if you require any further details please let me know.

**Comment by Poodmund** [comment]
I was just searching for DMagics fix for this and came across his Gist page with the code for the fix and thought it would be handy to leave here for reference: https://gist.github.com/DMagic1/a37765092758fcb29d3927b24d015d42

**Comment by sarbian** [comment]
Oh right, I keep forgetting to merge that!
I ll do it the weekend. Remind me again if I forget

**Comment by sarbian** [comment]
Done !
